name: Scrape Webpage

on:
  workflow_dispatch: # এটি ম্যানুয়ালি গিটহব থেকে রান করার সুবিধা দেবে

jobs:
  scrape:
    runs-on: ubuntu-latest

    # গিটহবে ফাইল পুশ করার জন্য পারমিশন দিতে হবে
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: playwright install --with-deps chromium

      - name: Run Python Script
        run: python main.py

      # জেনারেট হওয়া Row_Link ফোল্ডার এবং Status ফাইল গিটহব রিপোজটরিতে সেভ (Commit & Push) করার জন্য
      - name: Commit and push generated files
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add Row_Link/ status.txt
          git commit -m "Auto-generated multi-resolution M3U playlists and status [skip ci]" || echo "No changes to commit"
          git push
